Boltzmann
Astera-org/obelisk pull request #239
Opened 2022-08-16 00:11 UTC by qemqemqem

Got LVIS loaded and training but poorly

2022-08-24 19:33 UTC, garymm requested changes
* Delete optimize.thrift if it's not needed.
* Don't update submodules in this PR if not necessary
* Can we format all of our Python code with [Black](https://black.readthedocs.io/en/stable/)? I think it will make things much more readable. If that's acceptable I can add a check to CI.
* Can you delete some of the commented-out code? It's pretty distracting.

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/boltzmann.py
> +    # hyperparameter_grid_search(HParams(epochs=10, hidden_size=20, input_size=25, output_size=25, num_hidden_layers=2, num_rnn_steps=5, num_runs=2, dataset="ra25", layer_self_connections=False, laye
this is kinda hard to read. Can we put these into named functions that just don't get called rather than have all this commented out code?

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/boltzmann_script.py
> +    f = open("boltzmann.cfg", "r")
```python
with open("bolztmann.cfg") as f:
   ...
```

That will close it automatically.

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/boltzmann_script.py
> +        if "=" in line: # TOML files assign variables like this
Use a TOML parser library?

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/datasets.py
>  import math
You should generally try not use things from math or numpy when interacting with torch. It can be much slower than using the torch equivalents, especially when accelerators (e.g. GPU) are being used.

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/hparams_example.yaml
> +dataset: "xor"
can we stick to TOML or YAML for everything rather than some of each?

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/boltzmann.cfg
> +# TOML file. Values for an HParams object
can we name it .toml to make it obvious?

2022-08-24 19:33 UTC, garymm commented on models/pytorch/boltzmann/hparams_test.yaml
> +hidden_size: 10
add new line

2022-08-24 19:33 UTC, garymm commented on models/pytorch/classic_models/classic.py
> +#Author: Kevin McKee
can we split these into a separate PR authored by Kevin and omit the author info here?

2022-08-24 19:33 UTC, garymm commented on requirements.txt
> +torch~=1.12.0
We should have a discussion about requirements files, bazel, etc.
For the purposes of this PR, why do we have a new requirements at the root and a new requirements inside a subdir?

2022-09-13 01:35 UTC, qemqemqem commented on models/pytorch/boltzmann/boltzmann_script.py
> +        if "=" in line: # TOML files assign variables like this
TOML's very simple; I think it'll be less work to maintain this than to find a parser library.

2022-09-13 01:36 UTC, qemqemqem commented on models/pytorch/boltzmann/hparams_example.yaml
> +dataset: "xor"
We could. This yaml file isn't really used.

2022-09-13 01:37 UTC, qemqemqem commented on models/pytorch/boltzmann/datasets.py
>  import math
I think this isn't a problem in datasets.py, but this is good to note when thinking about optimization of the model.

2022-09-13 02:44 UTC, wumpusman approved these changes

2022-09-29 18:30 UTC, garymm commented
Can we close or merge this?

2022-10-07 15:03 UTC, closed without merging