add a bool for agent dead
Astera-org/obelisk pull request #367
Opened 2022-10-20 22:20 UTC by etuleu

2022-10-21 17:37 UTC, garymm requested changes

2022-10-21 17:37 UTC, garymm commented on models/agent/agent_interface.go
> +	Step(observations map[string]etensor.Tensor, debug string, isDead bool) (actions map[string]Action)
I think this is perhaps not the best name. E.g., if egan ends after a certain number of steps, the agent didn't die, so it's a bit misleading.
How's about something like "newWorld" or "worldStarting" or "agentPresent" (the last one would be a negation)?

2022-10-21 18:41 UTC, etuleu commented on models/agent/agent_interface.go
> +	Step(observations map[string]etensor.Tensor, debug string, isDead bool) (actions map[string]Action)
No, this flag actually means the agent is dead and has been removed from the world. The case where the world just ended but the agent hasn't died can be deduced from the tick counter and max steps which are passed in the observations dict.

2022-10-22 00:14 UTC, garymm commented
As discussed, please either close this or change it to `done`

2022-10-22 00:39 UTC, etuleu commented
> As discussed, please either close this or change it to `done`

Changed to done. Will update the egan side to make sense for the done sense as well.

2022-10-24 18:21 UTC, garymm approved these changes

2022-10-24 18:21 UTC, garymm commented on network/env.thrift
> +  Actions step(1:Observations observations, 2:string debug, 3:bool done)
please add a comment describing `done`

2022-10-24 22:10 UTC, merged